{
  "hash": "03c28daa4c70a9397699f77736169576",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Estadística I\"\nsubtitle: \"clase 14: coeficiente de correlación de Pearson\"\nformat: revealjs\ndate: \"2025/06/03\"\nlang: es\nincremental: true\nauto-stretch: false\nfig-align: center\nexecute:\n  echo: false\n  eval: true\n  fig-align: center\n---\n\n\n\n\n\n\n## Coeficiente de Correlación de Pearson\n\n-   El **coeficiente de correlación de Pearson** ($r$) es una medida estadística que cuantifica la **fuerza** y la **dirección** de la relación lineal entre dos variables cuantitativas.\n-   Es una herramienta fundamental en estadística para entender cómo se mueven dos variables de un mismo cojunto de datos en distintas observaciones.\n-   El valor de $r$ siempre se encuentra entre -1 y +1.\n\n------------------------------------------------------------------------\n\n## Interpretación del Coeficiente $r$\n\n-   $r > 0$: Indica una correlación **positiva**. A medida que una variable aumenta, la otra tiende a aumentar.\n-   $r < 0$: Indica una correlación **negativa**. A medida que una variable aumenta, la otra tiende a disminuir.\n-   $r \\approx 0$: Indica una correlación **débil** o nula entre las variables.\n-   La magnitud de $r$ indica la fuerza de la relación lineal:\n    -   Cercano a $\\pm 1$: Correlación lineal fuerte.\n    -   Cercano a 0: Correlación lineal débil.\n\n------------------------------------------------------------------------\n\n## La Fórmula del Coeficiente de Correlación de Pearson\n\nEl coeficiente de correlación de Pearson se calcula mediante la siguiente fórmula:\n\n$$r = \\frac{\\sum_{i=1}^{n} (x_i - \\bar{x})(y_i - \\bar{y})}{\\sqrt{\\sum_{i=1}^{n} (x_i - \\bar{x})^2} \\sqrt{\\sum_{i=1}^{n} (y_i - \\bar{y})^2}}$$\n\nDonde: \\* $n$ es el número de pares de datos. \\* $x_i$ y $y_i$ son los valores individuales de las dos variables. \\* $\\bar{x}$ es la media de los valores de $x$. \\* $\\bar{y}$ es la media de los valores de $y$.\n\n------------------------------------------------------------------------\n\n## Ejemplo de Cálculo\n\nConsideremos el siguiente conjunto de datos sobre horas de estudio ($X$) y calificaciones obtenidas ($Y$):\n\n| Estudiante | Horas de Estudio ($X$) | Calificación ($Y$) |\n|:----------:|:----------------------:|:------------------:|\n|     1      |           2            |         5          |\n|     2      |           3            |         7          |\n|     3      |           4            |         8          |\n\n## Gráfico de Dispersión\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](clase_14_02coefR_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n## Ejemplo de Cálculo-cont.\n\nVamos a calcular el coeficiente de correlación $r$.\n\nPrimero, calculamos las medias:\n\n<br>\n\n$$\\bar{x} = \\frac{2+3+4}{3} = 3$$\n\n<br>\n\n$$\\bar{y} = \\frac{5+7+8}{3} \\approx 6.67$$\n\nLuego, calculamos los términos necesarios para la fórmula:\n\n## Ejemplo de Cálculo-cont. {style=\".small\"}\n\n| $x_i$ | $y_i$ | $x_i - \\bar{x}$ | $y_i - \\bar{y}$ | $(x_i - \\bar{x})(y_i - \\bar{y})$ | $(x_i - \\bar{x})^2$ | $(y_i - \\bar{y})^2$ |\n|:--:|:--:|:--:|:--:|:--:|:--:|:--:|\n| 2 | 5 | -1 | -1.67 | 1.67 | 1 | 2.79 |\n| 3 | 7 | 0 | 0.33 | 0 | 0 | 0.11 |\n| 4 | 8 | 1 | 1.33 | 1.33 | 1 | 1.77 |\n|  |  |  |  | $\\sum = 3.00$ | $\\sum = 2$ | $\\sum = 4.67$ |\n\n------------------------------------------------------------------------\n\n## Resultado del Ejemplo\n\nSustituyendo los valores en la fórmula:\n\n$$r = \\frac{3.00}{\\sqrt{2} \\sqrt{4.67}} = \\frac{3.00}{\\sqrt{9.34}} \\approx \\frac{3.00}{3.06} \\approx 0.98$$\n\n-   El valor de $r \\approx 0.98$ indica una **correlación lineal positiva muy fuerte** entre las horas de estudio y las calificaciones obtenidas en este pequeño conjunto de datos. Esto sugiere que a mayor número de horas de estudio, tiende a haber una mayor calificación.\n",
    "supporting": [
      "clase_14_02coefR_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}